os:
 - osx
 - linux

language: cpp
compiler:
 - clang

before_install:
 - cd .. && git clone --recursive https://github.com/VCVRack/Rack.git
 - mv VCVRack-Simple ./Rack/plugins/VCVRack-Simple
 - cd Rack
 - make dep && make

script:
 - make allplugins
