os: osx
language: cpp
compiler:
- clang

before_install:
- cd .. && git clone --recursive https://github.com/VCVRack/Rack.git
- mv Simple Rack/plugins/Simple
- cd Rack
- make dep && make

script:
- make allplugins
