language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - llvm-toolchain-trusty-5.0
           packages:
             - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="rm -fr /usr/local/include/c++ && brew update && brew install gcc && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode8.3

before_install:
 - eval "${MATRIX_EVAL}"
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xorg-dev libglu1-mesa-dev libasound2-dev libgtk2.0-dev; fi
 - cd .. && git clone --recursive https://github.com/VCVRack/Rack.git
 - mv VCVRack-Simple ./Rack/plugins/VCVRack-Simple
 - cd Rack
 - make dep && make

script:
 - make allplugins
