language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - libasound2-dev
            - libgtk2.0-dev
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
 - RACK_GIT_COMMIT=8e251c0ddbfc1f4a2e03a6123d8eda42218b76fe
 - eval "${MATRIX_EVAL}"
 - cd .. && git clone --recursive https://github.com/VCVRack/Rack.git
 - cd ./Rack && git reset --hard "${RACK_GIT_COMMIT}" && git submodule update && cd ..
 - mv VCVRack-Simple ./Rack/plugins/VCVRack-Simple
 - cd Rack
 - make dep && make

script:
 - make allplugins
